apiVersion: v1
kind: Secret
metadata:
  name: victoria-basic-auth-secret
  namespace: victoria
type: Opaque
data:
  users: bWFybGFtOiQyeSQwNSRPQXFqTTB3SUpwbXF0WjVKS1NtaG5lMGNiR3ZMTWhvQ3h2UUJkRHV0Ti9pRC5hdzhBLndWSw==