apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-pv-config
  namespace: media
  labels:
    app: nzbget
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi