apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pv-config
  namespace: media
  labels:
    app: plex
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pv-transcode
  namespace: media
  labels:
    app: plex
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi