apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-password
  namespace: homeassistant
  labels:
    app: mosquitto
data:
  password.txt: |
    mqtt:$2y$05$6SjAgpgWaUigP9sgbiBedOoP4N9PfaBK7TempdhFfHCBBfPu.tER.