apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-password
  namespace: homeassistant
  labels:
    app: mosquitto
data:
  password.txt: |
    mqtt:$7$101$XxaJUYWLzo+cXDOI$0EGXBtGTgyMSp5u+3fxYwdCIuvCIj1EPb0hT7VHn1ZZuMAXFNQyfjMh5bLGYcSzatIv65GqehI3DiN09Wer0ow==