apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: cert-manager
  interval: 10m
  releaseName: cert-manager
  targetNamespace: cert-manager
  values:
    installCRDs: true
    crds:
      enable: true
  install:
    crds: CreateReplace
    createNamespace: true
  upgrade:
    crds: CreateReplace