apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: loki
      version: "2.10.3"
  interval: 10m
  releaseName: loki
  targetNamespace: loki
  install:
    crds: Create
  upgrade:
    crds: CreateReplace